services:
  # The API service handles all requests from the frontend
  api:
    build: ./api
    env_file:
      - ./api/.env
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app

  # The frontend service will serve the Next.js app
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api
    command: npm run dev
